In [9]:
import requests
import pandas as pd
import chess.pgn
import io
from datetime import datetime

USERNAME = "raizeraaa"
headers = {"User-Agent": "chess-data-analysis/1.0 raipex.dev@gmail.com"}

# Coletar todos os meses disponíveis
url_arquivos = f"https://api.chess.com/pub/player/{USERNAME}/games/archives"
meses = requests.get(url_arquivos, headers=headers).json()["archives"]
print(f"Total de meses: {len(meses)}")

Total de meses: 40

Collecting chess
  Using cached chess-1.11.2.tar.gz (6.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: chess
  Building wheel for chess (pyproject.toml): started
  Building wheel for chess (pyproject.toml): finished with status 'done'
  Created wheel for chess: filename=chess-1.11.2-py3-none-any.whl size=147919 sha256=9240fedf5ee3c781c4d4deee723b3d6b1993a208c2c1647cd705a7d089b28444
  Stored in directory: c:\users\rppp\appdata\local\pip\cache\wheels\74\65\99\8c3a88ba852c1ed8d34daed144b8cb4c654d638677483d19ff
Successfully built chess
Installing collected packages: chess
Successfully installed chess-1.11.2
Note: you may need to restart the kernel to use updated packages.

In [31]:
# Corrigir o DataFrame existente — recriar coluna data com horário
# O problema foi que salvamos só a data no parsear_partida
# Precisamos refazer a coleta salvando datetime completo

def parsear_partida_v2(jogo, username):
    if jogo["white"]["username"].lower() == username.lower():
        cor = "white"
        cor_adversario = "black"
    else:
        cor = "black"
        cor_adversario = "white"

    resultado_raw = jogo[cor]["result"]
    if resultado_raw == "win":
        resultado = "vitoria"
    elif resultado_raw in ["checkmated", "timeout", "resigned", "lose"]:
        resultado = "derrota"
    else:
        resultado = "empate"

    acuracia = None
    if "accuracies" in jogo:
        acuracia = jogo["accuracies"].get(cor)

    import chess.pgn, io
    pgn_io = io.StringIO(jogo["pgn"])
    game = chess.pgn.read_game(pgn_io)
    headers_pgn = game.headers if game else {}

    eco_url = jogo.get("eco", "")
    eco_code = eco_url.split("/")[-1].split("-")[0] if eco_url else "?"
    abertura_nome = headers_pgn.get("ECOUrl", "").split("/")[-1].replace("-", " ") if game else "?"

    # CORRIGIDO — salvar datetime completo com hora
    data_ts = jogo.get("end_time")
    data_completa = datetime.fromtimestamp(data_ts) if data_ts else None

    return {
        "uuid":              jogo.get("uuid"),
        "data":              data_completa,          # datetime completo
        "hora":              data_completa.hour if data_completa else None,
        "cor":               cor,
        "resultado":         resultado,
        "tipo":              jogo.get("time_class"),
        "tempo_controle":    jogo.get("time_control"),
        "rating_proprio":    jogo[cor]["rating"],
        "rating_adversario": jogo[cor_adversario]["rating"],
        "adversario":        jogo[cor_adversario]["username"],
        "acuracia_pct":      acuracia,
        "eco_code":          eco_code,
        "abertura":          abertura_nome,
        "url":               jogo.get("url"),
    }

print("Função v2 criada!")

Função v2 criada!

In [32]:
# Recoletando todas as partidas com horário correto
url_arquivos = f"https://api.chess.com/pub/player/{USERNAME}/games/archives"
meses = requests.get(url_arquivos, headers=headers).json()["archives"]

todas_partidas_v2 = []

for i, url_mes in enumerate(meses):
    response = requests.get(url_mes, headers=headers)
    partidas_mes = response.json().get("games", [])

    for jogo in partidas_mes:
        if jogo.get("rules") == "chess":
            try:
                dados = parsear_partida_v2(jogo, USERNAME)
                todas_partidas_v2.append(dados)
            except:
                pass

    print(f"[{i+1}/{len(meses)}] coletado")

df_v2 = pd.DataFrame(todas_partidas_v2)
df_v2 = df_v2.sort_values("data").reset_index(drop=True)
print(f"\nTotal: {len(df_v2)} partidas")
print(f"Horas únicas: {df_v2['hora'].nunique()}")
print(df_v2["hora"].value_counts().head(5))

[1/40] coletado
[2/40] coletado
[3/40] coletado
[4/40] coletado
[5/40] coletado
[6/40] coletado
[7/40] coletado
[8/40] coletado
[9/40] coletado
[10/40] coletado
[11/40] coletado
[12/40] coletado
[13/40] coletado
[14/40] coletado
[15/40] coletado
[16/40] coletado
[17/40] coletado
[18/40] coletado
[19/40] coletado
[20/40] coletado
[21/40] coletado
[22/40] coletado
[23/40] coletado
[24/40] coletado
[25/40] coletado
[26/40] coletado
[27/40] coletado
[28/40] coletado
[29/40] coletado
[30/40] coletado
[31/40] coletado
[32/40] coletado
[33/40] coletado
[34/40] coletado
[35/40] coletado
[36/40] coletado
[37/40] coletado
[38/40] coletado
[39/40] coletado
[40/40] coletado

Total: 4076 partidas
Horas únicas: 24
hora
17    423
19    420
20    382
21    365
22    317
Name: count, dtype: int64

In [33]:
# Criar DataFrame
df = pd.DataFrame(todas_partidas)
df["data"] = pd.to_datetime(df["data"])
df = df.sort_values("data").reset_index(drop=True)

print(df.shape)
print(df.dtypes)
df.head()

(4076, 13)
uuid                         object
data                 datetime64[ns]
cor                          object
resultado                    object
tipo                         object
tempo_controle               object
rating_proprio                int64
rating_adversario             int64
adversario                   object
acuracia_pct                float64
eco_code                     object
abertura                     object
url                          object
dtype: object

,uuid,data,cor,resultado,tipo,tempo_controle,rating_proprio,rating_adversario,adversario,acuracia_pct,eco_code,abertura,url
0,ca1804fb-a239-11ec-a864-78ac4409ff3c,2022-03-12,white,derrota,rapid,1800,648,1114,elbinhavermelha,NaN,Kings,Kings Pawn Opening Kings Knight Variation 2...Nc6,https://www.chess.com/game/live/40852123307
1,ada5174f-a3d2-11ec-a9b5-78ac4409ff3c,2022-03-14,black,derrota,blitz,300,700,718,elbinhavermelha,NaN,Sicilian,Sicilian Defense Bowdler Attack 2...Nc6,https://www.chess.com/game/live/41027433329
2,0f77b419-a3d4-11ec-a9b5-78ac4409ff3c,2022-03-14,white,derrota,rapid,600,648,1114,elbinhavermelha,NaN,Philidor,Philidor Defense 3.Nc3,https://www.chess.com/game/live/41028031299
3,85b6a5f2-4b06-11ed-bce6-78ac4409ff3c,2022-10-13,black,derrota,rapid,1800,292,334,gustavoferreira554,NaN,Kings,Kings Pawn Opening 1...e5,https://www.chess.com/game/live/59411505849
4,de570673-4b08-11ed-bce6-78ac4409ff3c,2022-10-13,white,derrota,rapid,1800,174,369,gustavoferreira554,NaN,Vienna,Vienna Game,https://www.chess.com/game/live/59412647389

In [17]:
# Primeiros insights
print("=== Resumo geral ===")
print(f"Total de partidas:  {len(df)}")
print(f"Período:            {df['data'].min().date()} → {df['data'].max().date()}")
print(f"\nPor tipo:")
print(df["tipo"].value_counts())
print(f"\nResultados gerais:")
print(df["resultado"].value_counts())
print(f"\nAcurácia média:     {df['acuracia_pct'].mean():.1f}%")
print(f"\nTop 5 aberturas:")
print(df["abertura"].value_counts().head())

=== Resumo geral ===
Total de partidas:  4076
Período:            2022-03-12 → 2026-04-24

Por tipo:
tipo
rapid     4001
blitz       47
bullet      19
daily        9
Name: count, dtype: int64

Resultados gerais:
resultado
vitoria    2019
derrota    1913
empate      144
Name: count, dtype: int64

Acurácia média:     67.9%

Top 5 aberturas:
abertura
Caro Kann Defense                       104
Queens Gambit Accepted Old Variation     60
Alekhines Defense                        49
Sicilian Defense                         47
Kings Pawn Opening 1...e5                39
Name: count, dtype: int64

In [18]:
# Salvar dados brutos
df.to_csv(
    r"C:\chess-data-analysis\data\processed\partidas_raizeraaa.csv",
    index=False,
    sep=";",
    encoding="utf-8-sig"
)
print(f"Salvo: {len(df)} partidas")

Salvo: 4076 partidas

In [19]:
# Taxa de vitória por abertura — mínimo 10 partidas para ser relevante
df_aberturas = df.groupby("abertura").agg(
    total=("resultado", "count"),
    vitorias=("resultado", lambda x: (x == "vitoria").sum()),
    acuracia_media=("acuracia_pct", "mean")
).reset_index()

df_aberturas["taxa_vitoria_pct"] = (
    df_aberturas["vitorias"] / df_aberturas["total"] * 100
).round(1)

df_aberturas = df_aberturas[df_aberturas["total"] >= 10]
df_aberturas = df_aberturas.sort_values("taxa_vitoria_pct", ascending=False)

print("=== Suas melhores aberturas (min 10 partidas) ===")
df_aberturas[["abertura", "total", "taxa_vitoria_pct", "acuracia_media"]].head(10)

=== Suas melhores aberturas (min 10 partidas) ===

,abertura,total,taxa_vitoria_pct,acuracia_media
436,Indian Game Knights Variation 2...e6 3.Nc3 d5,10,90.0,71.755000
308,French Defense,15,80.0,65.575000
794,Queens Gambit Declined 3.e3,15,80.0,80.055000
860,Queens Pawn Opening 1...d5,15,73.3,60.730000
1295,Van t Kruijs Opening 1...e5,11,72.7,73.710000
680,Pirc Defense,11,72.7,68.600000
547,Modern Defense with 1 d4,17,70.6,63.342000
775,Queens Gambit Accepted Old Variation 3...e6 4....,10,70.0,66.983333
869,Queens Pawn Opening 1...d6,10,70.0,48.520000
873,Queens Pawn Opening Accelerated London System,12,66.7,68.300000

In [20]:
# Performance por cor
print("=== Brancas vs Pretas ===")
df.groupby("cor").agg(
    total=("resultado", "count"),
    taxa_vitoria=("resultado", lambda x: f"{(x=='vitoria').mean()*100:.1f}%"),
    acuracia_media=("acuracia_pct", lambda x: f"{x.mean():.1f}%")
).reset_index()

=== Brancas vs Pretas ===

     cor  total taxa_vitoria acuracia_media
0  black   2044        47.7%          67.7%
1  white   2032        51.4%          68.2%

In [21]:
# Evolução do rating ao longo do tempo
df["mes"] = df["data"].dt.to_period("M")

df_rating = df.groupby("mes").agg(
    rating_medio=("rating_proprio", "mean"),
    partidas=("uuid", "count")
).reset_index()

df_rating["mes"] = df_rating["mes"].astype(str)
print("=== Evolução do rating ===")
print(df_rating.tail(12))

=== Evolução do rating ===
        mes  rating_medio  partidas
28  2025-05    841.000000        47
29  2025-06    806.905660        53
30  2025-07    889.710145        69
31  2025-08    862.395833        48
32  2025-09    792.000000        41
33  2025-10    790.903846        52
34  2025-11    814.902174        92
35  2025-12    902.173611       144
36  2026-01    887.915094       106
37  2026-02    811.762712        59
38  2026-03    734.730769       130
39  2026-04    788.644860       107

In [22]:
# Aberturas mais jogadas com cor
print("=== Top aberturas por cor ===")
df.groupby(["cor", "abertura"]).size().reset_index(name="total")\
  .sort_values(["cor", "total"], ascending=[True, False])\
  .groupby("cor").head(5)

=== Top aberturas por cor ===

        cor                                  abertura  total
54    black                         Caro Kann Defense    103
578   black                          Sicilian Defense     47
16    black                         Alekhines Defense     46
316   black                 Kings Pawn Opening 1...e5     34
715   black              Van t Kruijs Opening 1...Nf6     28
1150  white      Queens Gambit Accepted Old Variation     60
1126  white  Queens Gambit Accepted Central Variation     39
875   white                     Englund Gambit 2.dxe5     35
874   white                            Englund Gambit     30
1301  white  Queens Pawn Opening Horwitz Defense 2.c4     26

In [23]:
# Taxa de vitória do Caro-Kann especificamente
caro_kann = df[df["abertura"].str.contains("Caro", na=False)]
print(f"=== Caro-Kann ===")
print(f"Total de partidas:  {len(caro_kann)}")
print(f"Vitórias:           {(caro_kann['resultado']=='vitoria').sum()}")
print(f"Derrotas:           {(caro_kann['resultado']=='derrota').sum()}")
print(f"Taxa de vitória:    {(caro_kann['resultado']=='vitoria').mean()*100:.1f}%")
print(f"Acurácia média:     {caro_kann['acuracia_pct'].mean():.1f}%")

=== Caro-Kann ===
Total de partidas:  452
Vitórias:           206
Derrotas:           225
Taxa de vitória:    45.6%
Acurácia média:     68.0%

In [24]:
# Correlação entre acurácia e resultado
print("=== Acurácia média por resultado ===")
df.groupby("resultado")["acuracia_pct"].mean().round(1)

=== Acurácia média por resultado ===

resultado
derrota    60.2
empate     68.0
vitoria    73.6
Name: acuracia_pct, dtype: float64

In [25]:
# Meses com mais derrotas — identificar tilt
df["mes_str"] = df["data"].dt.to_period("M").astype(str)

df_mensal = df.groupby("mes_str").agg(
    total=("resultado", "count"),
    vitorias=("resultado", lambda x: (x=="vitoria").sum()),
    derrotas=("resultado", lambda x: (x=="derrota").sum()),
    acuracia=("acuracia_pct", "mean")
).reset_index()

df_mensal["taxa_vitoria"] = (df_mensal["vitorias"] / df_mensal["total"] * 100).round(1)
print("=== Últimos 6 meses ===")
print(df_mensal.tail(6).to_string())

=== Últimos 6 meses ===
    mes_str  total  vitorias  derrotas   acuracia  taxa_vitoria
34  2025-11     92        53        35  74.083684          57.6
35  2025-12    144        69        70  71.131959          47.9
36  2026-01    106        46        58  69.861200          43.4
37  2026-02     59        27        32  67.929545          45.8
38  2026-03    130        70        59  69.698904          53.8
39  2026-04    107        50        54  70.211127          46.7

In [26]:
# Performance por cor detalhada
print("=== Performance brancas vs pretas ===")
df.groupby("cor").agg(
    total=("resultado", "count"),
    taxa_vitoria=("resultado", lambda x: round((x=="vitoria").mean()*100, 1)),
    acuracia_media=("acuracia_pct", lambda x: round(x.mean(), 1)),
    rating_medio=("rating_proprio", "mean")
).round(1).reset_index()

=== Performance brancas vs pretas ===

     cor  total  taxa_vitoria  acuracia_media  rating_medio
0  black   2044          47.7            67.7         671.0
1  white   2032          51.4            68.2         671.3

In [29]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:suasenha@localhost:5432/chess_db")

# Criar banco antes se necessário — rode no PgAdmin:
# CREATE DATABASE chess_db;
df["mes"] = df["mes"].astype(str)
df.to_sql("partidas", engine, if_exists="replace", index=False)
print(f"Salvo no PostgreSQL: {len(df)} partidas")

Salvo no PostgreSQL: 4076 partidas

In [30]:
# Salvar também o CSV processado
df.to_csv(
    r"C:\chess-data-analysis\data\processed\partidas_raizeraaa.csv",
    index=False,
    sep=";",
    encoding="utf-8-sig"
)
print("CSV salvo!")

CSV salvo!